# Generated by Django 5.1.6 on 2025-05-13 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_inventario_delete_entradainventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='proveedor',
        ),
    ]
