# Generated by Django 5.1.6 on 2025-05-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_inventario_cantidad_alter_inventario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste de precios'), ('vencimiento', 'Salida por vencimiento'), ('daño', 'Salida por daño'), ('pérdida', 'Salida por pérdida')], default='entrada', max_length=15),
        ),
    ]
