# Generated by Django 5.1.6 on 2025-05-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(blank=True, help_text='Estado real del pago en Mercado Pago (approved, rejected, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='payment_id',
            field=models.CharField(blank=True, help_text='ID del pago en Mercado Pago', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='preferencia_id',
            field=models.CharField(blank=True, help_text='ID de preferencia de Mercado Pago', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('anulada', 'Anulada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('mercadopago', 'Mercado Pago')], max_length=20),
        ),
    ]
