# Generated by Django 5.1.6 on 2025-05-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('recibido', 'Recibido'), ('incompleto', 'Incompleto'), ('cancelado', 'Cancelado'), ('en proceso', 'En Proceso')], default='pendiente', max_length=20),
        ),
    ]
