# Generated by Django 5.1.6 on 2025-04-20 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_remove_producto_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='activo',
        ),
    ]
