# Generated by Django 5.1.6 on 2025-04-21 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_categoria_producto_stock_and_more'),
        ('proveedores', '0004_remove_proveedor_dias_visita_delete_diavisita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='proveedores.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(default='unidad', max_length=20),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
