# Generated by Django 5.1.6 on 2025-04-17 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaProveedor',
            new_name='Categoria',
        ),
    ]
