# Generated by Django 5.1.6 on 2025-04-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_rename_categoriaproveedor_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='dias_visita',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dias_visita',
            field=models.ManyToManyField(blank=True, related_name='proveedores', to='proveedores.diavisita'),
        ),
    ]
