# Generated by Django 5.1.6 on 2025-04-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_diavisita_remove_proveedor_dias_visita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='dias_visita',
        ),
        migrations.DeleteModel(
            name='DiaVisita',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dias_visita',
            field=models.CharField(default='Lunes', max_length=255),
        ),
    ]
