# Generated by Django 5.1.6 on 2025-05-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_remove_proveedor_dias_visita_delete_diavisita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='dias_visita',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254, unique=True),
        ),
    ]
